#!/bin/bash
# Open a file from command line, multi OS

# Miki Tebeka <miki.tebeka@gmail.com>

if [ $# -ne 1 ]; then
    echo "usage: `basename $0` PATH"
    exit 1
fi

case `uname` in
    Linux) open=exo-open;;
    Darwin) open=open;;
    CYGWIN*) open=cygstart;;
    MINGW*) open=start;;
    *) echo "error: no start program for `uname` platform" 1>&2; exit 1;;
esac

$open "$1" > /dev/null 2>&1
